port: 8000
whitelist:
  - 127.0.0.1
  - 192.168.86.31
  - 192.168.1.120
  - 192.168.86.64
  - 192.168.86.21
  - 192.168.1.60
  - 192.168.1.57
whitelistMode: true
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
autorun: true
enableExtensions: true
listen: true
disableThumbnails: false
allowKeysExposure: false
securityOverride: false
skipContentCheck: false
enableCorsProxy: false
thumbnailsQuality: 95
disableChatBackup: false
requestOverrides: []
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Xenova/all-mpnet-base-v2
  promptExpansionModel: Cohee/fooocus_expansion-onnx
openai:
  randomizeUserId: false
deepl:
  formality: default
